//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {         
        public string StatusContractName { set; get; }
        public string OrganizationUnitName { set; get; }
        public string ContactCountryName { set; get; }
        public string BranchName { set; get; }
        public string GenderName { set; get; }
        public string OfficeName { set; get; }
        public string CompanyName { set; get; }
        public string OfficePositionName { set; get; }
        public int WorkingDayMachineID { set; get; }
        public int WorkingManagerID { set; get; }
        public int WorkingHRID { set; get; }
        public bool OnlyApproveDirectManagerialStaff { set; get; }
        public string StatusName { set; get; }
        public string DeptChild { set; get; }
        public string UserName { set; get; }
        public bool IsActivated { set; get; }
        public int RoleID { set; get; }
        public string WPTypeName { set; get; }
        public string DecisionNo { set; get; }
        public DateTime? WPStartDate { set; get; }
        public DateTime? WPEndDate { set; get; }
        public string WPNote { set; get; }
        public string OfficeRole { set; get; }
        public string Rank { set; get; }
        public string ContractType { set; get; }
        public DateTime? StartDateContract { set; get; }
        public DateTime? EndDateContract { set; get; }
        public string ContractNo { set; get; }
        public string Currency { set; get; }
        public double BasicPay { set; get; }
        public double EfficiencyBonus { set; get; }
        public string PolicyApplies { set; get; }
        public string Manager { set; get; }
        public double SumAllowance { set; get; }
        public string BrowsingStatus { set; get; }
        public string HRIdsName { set; get; }
        public int StatusContractID { set; get; }
        public string OrganizationUnitNameExcel { set; get; }
    }
}
