//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalHistory
    {
         
        public int AutoID { get; set; }
        public int IDofTable { get; set; }
        public int Status { get; set; }
        public string TableName { get; set; }
        public string Note { get; set; }
        public int SubmittedBy { get; set; }
        public DateTime? SubmittedDate { get; set; }
        
    }
}
