//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    

    public partial class Department
    {
        public int id { get; set; }
        public string label { get; set; }
        public string Name { get; set; }
        public string NameEN { get; set; }
        public int ParentID { get; set; }
        public string Value { get; set; }
        public bool? collapsed { get; set; }
        public List<Department> children { get; set; } 
    }
}
