//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int StaffID { get; set; }
        public int UserID { get; set; }
        public string StaffCode { get; set; }
        public string FullName { get; set; }
        public string FullNameEN { get; set; }
        public int OrganizationUnitID { get; set; }
        public int OfficePositionID { get; set; }
        public string IdentityNumber { get; set; }
        public DateTime? IDIssuedDate { get; set; }
        public string IDIssuedBy { get; set; }
        public string TaxID { get; set; }
        public DateTime? TaxDate { get; set; }
        public string TaxBy { get; set; }
        public string BankNumber { get; set; }
        public string BankName { get; set; }
        public DateTime? BirthDay { set; get; }
        public int Status { get; set; }
        public int GenderID { get; set; }
        public string Address { get; set; }
        public int CountryID { get; set; }
        public int ProvinceID { get; set; }
        public string ContactAddress { get; set; }
        public int ContactCountryID { get; set; }
        public int ContactProvinceID { get; set; }
        public string PhoneEx { get; set; }
        public string Mobile { get; set; }
        public string Skype { get; set; }
        public string LinkFacebook { get; set; }
        public int ParentID { get; set; }
        public string imageLink { get; set; }
        public int StaffLevel { get; set; }
        public string EmailCompany { get; set; }
        public string EmailPersonal { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string AddressOfContact { get; set; }
        public int Ds_StatusContractID { get; set; }
        public bool HoldSaraly { get; set; }
        public int TreeLevel { get; set; }
        public bool HasChild { get; set; }
        public string MCCs { get; set; }
        public string BMs { get; set; }
        public string SSN { get; set; }
        public DateTime? LastChildBirthday { get; set; }
        public DateTime? StartWorkingDate { get; set; }
        public DateTime? TrialDate { get; set; }
        public DateTime? OfficialDate { get; set; }
        public DateTime? EndWorkingDate { get; set; }
        public float CommitmentBudgetLimit { get; set; }
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public int BranchId { get; set; }
        public bool IsApprovementDirectManager { get; set; }
        public string Password { set; get;}
        public string PasswordRepeat { set; get; }
        public string HRIds { set; get; }
        public string AcountName { set; get; }
        public string Note { set; get; }
        public string NamePB { set; get; }
    }
}
