//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class GlobalList
    {
        public int GlobalListID { get; set; }
        public string Name { get; set; }
        public string NameEN { get; set; }
        public string Value { get; set; }
        public string ValueEN { get; set; }
        public bool IsActive { get; set; }
        public string IsActive1 { get; set; }
        public string Descriptions { get; set; }
        public int ParentDetailID { get; set; }
        public int ParentID { get; set; }
        public int TreeLevel { get; set; }
        public bool HasChild { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public string CreatedBy1 { get; set; }
        public string ModifiedBy1 { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> idOld { get; set; }
        public string ListChildID { get; set; }
    }
}
