//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationUnit
    {
        public int OrganizationUnitID { get; set; }
        public string OrganizationUnitCode { get; set; }
        public string Name { get; set; }
        public string NameEN { get; set; }
        public int? ParentID { get; set; }
        public Nullable<int> DS_BranchID { get; set; }
        public Nullable<int> DS_CompanyID { get; set; }
        public Nullable<int> DS_UnitID { get; set; }
        public Nullable<int> DS_BUID { get; set; }
        public int TreeLevel { get; set; }
        public bool HasChild { get; set; }
        public int OrderNo { get; set; }
        public int? Status { get; set; }
        public bool IsImplementationReport { get; set; }
        public Nullable<int> Type { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<double> CommitmentBudgetLimit { get; set; }
        public Nullable<double> MarginMultiplierRate { get; set; }
        public Nullable<int> CompanyType { get; set; }
        public Nullable<int> CurrencyTypeID { get; set; }
        public List<OrganizationUnit> Childrens { get; set; }
        public int Id { get; set; }
        public string Label { get; set; }
        public bool? collapsed { get; set; }
        public List<OrganizationUnit> children { get; set; }
        public int  RoleId { get; set; }
    }
}
