//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalIncomeTaxRateDetail
    {
        public int PersonalIncomeTaxRateDetailId { get; set; }
        public int PersonalIncomeTaxRateId { get; set; }
        public double FromAmount { get; set; }
        public double ToAmount { get; set; }
        public double Rate { get; set; }
        public string Math { get; set; }
    }
}
