//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public byte RegionId { get; set; }
        public string RegionName { get; set; }
        public string RegionIdentity { get; set; }
        public string RegionLogoUrl { get; set; }
        public int ParentId { get; set; }
        public byte RegionLvel { get; set; }
        public bool IsActive { get; set; }
        public byte PriorityNumber { get; set; }
    }
}
