//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalarySourceMapEmployeeDetail
    {
        public long SalarySourceDetailId { get; set; }
        public int SalarySourceId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public double Amout { get; set; }
        public string AmountEncode { get; set; }
        public int MonthApply { get; set; }
        public int YearApply { get; set; }
        public int Status { get; set; }
        public int CreateBy { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime ReleaseDate { get; set; }
    }
}
