//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalarySource
    {
        public int SalarySourceId { get; set; }
        public string ShortName { get; set; }
        public string Name { get; set; }
        public string Prifix { get; set; }
        public string Description { get; set; }
        public byte OrderNo { get; set; }
        public int Status { get; set; }
        public Nullable<bool> IsHardWage { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<bool> IsVisiableOnSalary { get; set; }
        public string Unit { get; set; }
        public string Formula { get; set; }
    }
}
