//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryProcess
    {
        public int SalaryProcessId { get; set; }
        public int SalaryId { get; set; }
        public System.DateTime ProcessDate { get; set; }
        public string ProcessContent { get; set; }
        public int? CreateBy { get; set; }
    }
}
