//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sec_User
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime PasswordExpiredDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public int CurrentLanguageID { get; set; }
        public int Status { get; set; }
        public int UserType { get; set; }
        public string DisplayName { get; set; }
        public bool IsLocked { get; set; }
        public bool IsActivated { get; set; }
        public Nullable<System.DateTime> LockedDate { get; set; }
        public Nullable<int> LockedBy { get; set; }
        public Nullable<System.DateTime> ActivatedDate { get; set; }
        public Nullable<int> ActivatedBy { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<int> UseridV1 { get; set; }
        public Nullable<int> CurrencyTypeID { get; set; }
        public string PasswordPrevious { get; set; }
        public Nullable<int> temp { get; set; }
        public Nullable<int> AutoAdsID { get; set; }
        public Nullable<int> ImportDataID { get; set; }
        public string DepartmentName { get; set; }
    }
}
