//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DataAccess.Entity
{
    using HRM.Constants;
    using HRM.Common;
    using System;
    using System.Collections.Generic;

    public partial class Sec_Menu
    {
        public int MenuID { get; set; }
        public Nullable<int> ControllerID { get; set; }
        public string Name { get; set; }
        public string NameEN { get; set; }
        public string ActionName { get; set; }
        public bool IncludeMenu { get; set; }
        public int MenuPositionID { get; set; }
        public int OrderNo { get; set; }
        public string CssIconClass { get; set; }
        public int ParentID { get; set; }
        public bool IsActive { get; set; }
        public string Param { get; set; }
        public string Url { get; set; }
        public int TreeLevel { get; set; }
        public bool HasChild { get; set; }
        public string MenuPositionName { set; get; }
        public string ParentName { set; get; }
        public string MenuName { get; set; }
        public string MenuName_EN { get; set; }
        public string MenuNameByLanguage
        {
            get
            {
                if (Global.CurrentLanguage == (int)Constant.numLanguage.EN)
                    return MenuName_EN;
                return MenuName;
            }
        }
        public List<Sec_Menu> SubMenu { get; set; }
    }
}
