//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class Sys_Table_Role_Action
    {
        public int Id { get; set; }
        public int TableId { get; set; }
        public int RoleId { get; set; }
        public int UserId { get; set; }
        public bool isAdd { get; set; }
        public bool isEdit { get; set; }
        public bool isDelete { get; set; }
        public bool isActive { get; set; }
        public bool isFilterButton { get; set; }
        public bool isExcel { get; set; }
        public  bool isImportExcel { get; set; }
        public bool? isSubmit { get; set; }
        public bool? isApproval { get; set; }
        public bool? isDisApproval { get; set; }
        public bool? isCopy { get; set; }
        public string AddUrl { get; set; }
        public string EditUrl { get; set; }
        public string DeleteUrl { get; set; }
        public string SubmitUrl { get; set; }
        public string ApprovalUrl { get; set; }
        public string DisApprovalUrl { get; set; }
        public DateTime CreateDate { get; set; }
        public int CreateBy { get; set; }
        public bool isIndex { get; set; }
        public bool isGet { get; set; }
    }

}
