//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
        public partial class Sys_Table
        {
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
            public Sys_Table()
            {
                this.Sys_Table_Column = new HashSet<Sys_Table_Column>();
                this.Sys_Table_Role_Action = new HashSet<Sys_Table_Role_Action>();
            }

            public int id { get; set; }
            public string TableName { get; set; }
            public string LinkGetData { get; set; }
            public string DataEditUrl { get; set; }
            public string EditUrl { get; set; }
            public string AddUrl { get; set; }
            public string ImportUrl { get; set; }
            public string DowmLoadFileTemplateImportUrl { get; set; }
        public string DeleteUrl { get; set; }
            public string ExcelUrl { get; set; }
            public int PageSize { get; set; }
            public string PageSizeList { get; set; }
            public string IdTable { get; set; }
            public string ClassTable { get; set; }
            public string PopupWidth { get; set; }
            public string PopupHeight { get; set; }
            public bool IsActive { get; set; }
            public System.DateTime CreateDate { get; set; }
            public int CreateBy { get; set; }
            public string Note { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
            public virtual ICollection<Sys_Table_Column> Sys_Table_Column { get; set; }
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
            public virtual ICollection<Sys_Table_Role_Action> Sys_Table_Role_Action { get; set; }
        
    }
}
