//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Table_Column_Role
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public int TableColumnId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateBy { get; set; }
        public bool isActive { get; set; }
        public int Order { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Sys_Table_Column Sys_Table_Column { get; set; }
    }
}
