//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Map_Language
    {
        public int Id { get; set; }
        public int TableOfId { get; set; }
        public string TableName { get; set; }
        public int LanguageId { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string ShortDescription { get; set; }
        public string Value { get; set; }
        public bool IsActive { get; set; }
    }
}
