//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace HRM.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Map_Role
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public byte RoleId { get; set; }
        public bool IsActive { get; set; }
    }
}
